version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile2
    working_dir: /api
    ports:
      - 9090:9090
    depends_on:
      - database
    links:
      - database:db
    command: "php  -S 0.0.0.0:9090 "

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      
    volumes:
      - .:/core
    ports:
      - 3000:3000

    image: app:react
    #container_name: react_container  
    command: npm run start

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 7070:80
    environment:
      - PMA_ARBITRARY=0
    depends_on:
      - database
    links:
      - database:db

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql


volumes:
  database:
      
      
